### ISSUE TITLE
module.json in zip incorrect, resulting in infinite updates

### ISSUE THREAD

**Issue by zarmstrong** [gsimon2/pf2e-inspire-courage#1]
The module.json in the zipped archive is version "0.1.0" while the module.json that foundry checks shows 1.0.0. This results in an infinite update loop.

**Comment by gsimon2** [comment]
Wow good catch. I am sorry for the inconvenience that this caused, but I have updated the 1.0.0 release so that the embedded module.json correctly reflects the version. Thanks for posting!
