### ISSUE TITLE
get unmaintained warning in v9/10

### ISSUE THREAD

**Issue by dharkus5000** [gsimon2/pf2e-inspire-courage#5]
i get the following warning every time i login to a world
PF2e Inspire Courage Button is unmaintained and may introduce stability issues to your game. main.bundle.js:19:699031

**Comment by gsimon2** [comment]
Thanks for the comment! 

I am a little behind on updating my modules to Foundry v10 but am currently working through them. I should have an update for this one soon!

**Comment by gsimon2** [comment]
The compatibility warning should be gone now with the newly released version 1.1.1. 

Thanks for posting!
